<?php

declare(strict_types=1);

namespace App;

/**
 * Paths de la API v1 para OpenAPI. Se fusionan con app/OpenApi.php al ejecutar l5-swagger:generate.
 * Rutas protegidas: usar Bearer token (Authorize en Swagger UI).
 *
 * @OA\PathItem(path="/api/v1/auth/forgot-password", post=@OA\Post(operationId="authForgotPassword", tags={"Auth"}, summary="Solicitar recuperación de contraseña", responses={@OA\Response(response=200, description="OK")}))
 * @OA\PathItem(path="/api/v1/auth/reset-password", post=@OA\Post(operationId="authResetPassword", tags={"Auth"}, summary="Restablecer contraseña con token", responses={@OA\Response(response=200, description="OK")}))
 * @OA\PathItem(path="/api/v1/auth/logout", post=@OA\Post(operationId="authLogout", tags={"Auth"}, summary="Cerrar sesión", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}))
 * @OA\PathItem(path="/api/v1/auth/change-password", post=@OA\Post(operationId="authChangePassword", tags={"Auth"}, summary="Cambiar contraseña (usuario autenticado)", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}))
 * @OA\PathItem(path="/api/v1/user", get=@OA\Get(operationId="userCurrent", tags={"User"}, summary="Usuario actual (legacy)", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}))
 * @OA\PathItem(path="/api/v1/user/profile", get=@OA\Get(operationId="userProfileShow", tags={"User"}, summary="Ver perfil", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}), put=@OA\Put(operationId="userProfileUpdate", tags={"User"}, summary="Actualizar perfil", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}))
 * @OA\PathItem(path="/api/v1/dashboard", get=@OA\Get(operationId="dashboardIndex", tags={"Dashboard"}, summary="Resumen del dashboard", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}))
 * @OA\PathItem(path="/api/v1/reports/detail", get=@OA\Get(operationId="reportsDetail", tags={"Reports"}, summary="Consulta detallada de tareas", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}))
 * @OA\PathItem(path="/api/v1/reports/by-client", get=@OA\Get(operationId="reportsByClient", tags={"Reports"}, summary="Informe agrupado por cliente", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}))
 * @OA\PathItem(path="/api/v1/reports/by-employee", get=@OA\Get(operationId="reportsByEmployee", tags={"Reports"}, summary="Informe agrupado por empleado", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}))
 * @OA\PathItem(path="/api/v1/reports/by-task-type", get=@OA\Get(operationId="reportsByTaskType", tags={"Reports"}, summary="Informe agrupado por tipo de tarea", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}))
 * @OA\PathItem(path="/api/v1/reports/by-date", get=@OA\Get(operationId="reportsByDate", tags={"Reports"}, summary="Informe agrupado por fecha", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}))
 * @OA\PathItem(path="/api/v1/clientes", get=@OA\Get(operationId="clientesIndex", tags={"Clientes"}, summary="Listar clientes", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}), post=@OA\Post(operationId="clientesStore", tags={"Clientes"}, summary="Crear cliente", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=201, description="Creado")}))
 * @OA\PathItem(path="/api/v1/clientes/{id}", get=@OA\Get(operationId="clientesShow", tags={"Clientes"}, summary="Ver cliente", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}), put=@OA\Put(operationId="clientesUpdate", tags={"Clientes"}, summary="Actualizar cliente", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}), delete=@OA\Delete(operationId="clientesDestroy", tags={"Clientes"}, summary="Eliminar cliente", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}))
 * @OA\PathItem(path="/api/v1/clientes/{id}/tipos-tarea", get=@OA\Get(operationId="clientesTiposTareaIndex", tags={"Clientes"}, summary="Tipos de tarea del cliente", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}), put=@OA\Put(operationId="clientesTiposTareaUpdate", tags={"Clientes"}, summary="Actualizar tipos de tarea del cliente", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}))
 * @OA\PathItem(path="/api/v1/tipos-cliente", get=@OA\Get(operationId="tiposClienteIndex", tags={"Clientes"}, summary="Listar tipos de cliente", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}), post=@OA\Post(operationId="tiposClienteStore", tags={"Clientes"}, summary="Crear tipo de cliente", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=201, description="Creado")}))
 * @OA\PathItem(path="/api/v1/tipos-cliente/{id}", get=@OA\Get(operationId="tiposClienteShow", tags={"Clientes"}, summary="Ver tipo de cliente", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}), put=@OA\Put(operationId="tiposClienteUpdate", tags={"Clientes"}, summary="Actualizar tipo de cliente", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}), delete=@OA\Delete(operationId="tiposClienteDestroy", tags={"Clientes"}, summary="Eliminar tipo de cliente", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}))
 * @OA\PathItem(path="/api/v1/empleados", get=@OA\Get(operationId="empleadosIndex", tags={"Empleados"}, summary="Listar empleados", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}), post=@OA\Post(operationId="empleadosStore", tags={"Empleados"}, summary="Crear empleado", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=201, description="Creado")}))
 * @OA\PathItem(path="/api/v1/empleados/{id}", get=@OA\Get(operationId="empleadosShow", tags={"Empleados"}, summary="Ver empleado", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}), put=@OA\Put(operationId="empleadosUpdate", tags={"Empleados"}, summary="Actualizar empleado", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}), delete=@OA\Delete(operationId="empleadosDestroy", tags={"Empleados"}, summary="Eliminar empleado", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}))
 * @OA\PathItem(path="/api/v1/tipos-tarea", get=@OA\Get(operationId="tiposTareaIndex", tags={"Tipos de tarea"}, summary="Listar tipos de tarea", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}), post=@OA\Post(operationId="tiposTareaStore", tags={"Tipos de tarea"}, summary="Crear tipo de tarea", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=201, description="Creado")}))
 * @OA\PathItem(path="/api/v1/tipos-tarea/{id}", get=@OA\Get(operationId="tiposTareaShow", tags={"Tipos de tarea"}, summary="Ver tipo de tarea", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}), put=@OA\Put(operationId="tiposTareaUpdate", tags={"Tipos de tarea"}, summary="Actualizar tipo de tarea", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}), delete=@OA\Delete(operationId="tiposTareaDestroy", tags={"Tipos de tarea"}, summary="Eliminar tipo de tarea", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}))
 * @OA\PathItem(path="/api/v1/tasks", get=@OA\Get(operationId="tasksIndex", tags={"Tasks"}, summary="Listar tareas propias (paginado, filtros)", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}), post=@OA\Post(operationId="tasksStore", tags={"Tasks"}, summary="Crear tarea", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=201, description="Creado")}))
 * @OA\PathItem(path="/api/v1/tasks/all", get=@OA\Get(operationId="tasksIndexAll", tags={"Tasks"}, summary="Listar todas las tareas (supervisores)", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}))
 * @OA\PathItem(path="/api/v1/tasks/clients", get=@OA\Get(operationId="tasksGetClients", tags={"Tasks"}, summary="Lista de clientes activos", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}))
 * @OA\PathItem(path="/api/v1/tasks/task-types", get=@OA\Get(operationId="tasksGetTaskTypes", tags={"Tasks"}, summary="Tipos de tarea disponibles", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}))
 * @OA\PathItem(path="/api/v1/tasks/employees", get=@OA\Get(operationId="tasksGetEmployees", tags={"Tasks"}, summary="Lista de empleados (supervisores)", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}))
 * @OA\PathItem(path="/api/v1/tasks/bulk-toggle-close", post=@OA\Post(operationId="tasksBulkToggleClose", tags={"Tasks"}, summary="Proceso masivo: cerrar/reabrir tareas seleccionadas", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}))
 * @OA\PathItem(path="/api/v1/tasks/{id}", get=@OA\Get(operationId="tasksShow", tags={"Tasks"}, summary="Ver/editar tarea", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}), put=@OA\Put(operationId="tasksUpdate", tags={"Tasks"}, summary="Actualizar tarea", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}), delete=@OA\Delete(operationId="tasksDestroy", tags={"Tasks"}, summary="Eliminar tarea", security={{ "bearerAuth": {} }}, responses={@OA\Response(response=200, description="OK")}))
 */
class OpenApiPaths
{
}
